# Generated by Django 5.0.6 on 2024-07-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forget_password_token',
        ),
    ]
