# Generated by Django 5.0.6 on 2024-07-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
