# Generated by Django 5.0.6 on 2024-07-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_likes'),
        ('users_auth', '0005_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='post.post'),
        ),
    ]
