# Generated by Django 5.0.6 on 2024-07-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_picture_post_media_file'),
        ('users_auth', '0006_alter_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_auth.profile'),
        ),
    ]
