# Generated by Django 5.0.6 on 2024-05-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_message_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
