# Generated by Django 5.0.6 on 2024-06-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
