# Generated by Django 5.0.6 on 2024-06-13 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric or contain underscores.', regex='^[a-zA-Z0-9_]*$')]),
        ),
    ]
